// app/manifest.ts
// Ties the icon set already generated by scripts/generate-icons.mjs to a name and theme
// colour, so "Add to Home Screen" on a patient's phone produces something branded
// instead of a bare URL tile. `standalone`, not `fullscreen` — a hospital site should
// keep the browser's own back/reload affordances, not hide them.

import type { MetadataRoute } from 'next'
import { siteConfig } from '@/lib/site-config'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${siteConfig.name}, ${siteConfig.city}`,
    short_name: siteConfig.shortName,
    description: siteConfig.description,
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#0F5B66', // Primary Teal — matches viewport.themeColor in app/layout.tsx
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  }
}
